### PR TITLE
chore: Adding flexibility to exclude the label in prometheus pusher

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

### CODE REVIEW

**Review by vigith — COMMENTED** [review]
Why do you want to exclude? Can't we just exclude by not creating a label?

**Comment by sarabala1979** [comment]
Basically, inference will copy all source labels and add them to new anomaly metrics. But if the user wants to exclude any metrics from the source. They can configure it here.

**Comment by nkoppisetty** [comment]
> Basically, inference will copy all source labels and add them to new anomaly metrics. But if the user wants to exclude any metrics from the source. They can configure it here.

No, we won't be adding all the src labels. We will only add what is required, as labels lead to high cardinality data. We wont need any feature to exclude labels, just adding labels feature will be useful.

**Comment by vigith** [comment]
> No, we won't be adding all the src labels. We will only add what is required, as labels lead to high cardinality data. We wont need any feature to exclude labels, just adding labels feature will be useful.

+1

**Review by nkoppisetty — APPROVED** [review]

**Pull request closed without merging**
